## code to prepare `macro_indicators` dataset goes here

structure(list(rowid = c(
  1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L,
  10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 18L, 19L, 20L, 21L, 24L,
  25L, 28L, 29L, 31L, 32L, 34L, 39L, 43L, 48L, 50L, 53L, 55L, 60L,
  61L, 66L, 78L, 86L, 95L, 98L, 99L, 102L, 105L, 107L, 110L, 113L,
  118L, 121L, 129L, 141L, 142L, 146L, 150L, 156L, 166L, 167L, 168L,
  172L, 173L, 178L, 186L, 187L, 212L, 217L, 220L, 235L, 242L, 251L,
  262L, 316L, 318L, 322L, 443L, 455L, 480L, 488L, 509L, 510L, 513L,
  546L, 653L
), indicator = c(
  "10-year treasury constant maturity minus 2-year treasury constant maturity",
  "federal funds effective rate", "consumer price index for all urban consumers: all items in u.s. city average",
  "10-year breakeven inflation rate", "real gross domestic product",
  "30-year fixed rate mortgage average in the united states", "gross domestic product",
  "market yield on u.s. treasury securities at 10-year constant maturity",
  "unemployment rate", "ice bofa us high yield index option-adjusted spread",
  "assets: total assets: total assets (less eliminations from consolidation): wednesday level",
  "m2", "m1", "s&p/case-shiller u.s. national home price index",
  "market yield on u.s. treasury securities at 10-year constant maturity, inflation-indexed",
  "10-year treasury constant maturity minus 3-month treasury constant maturity",
  "velocity of m2 money stock", "overnight reverse repurchase agreements: treasury securities sold by the federal reserve in the temporary open market operations",
  "median sales price of houses sold for the united states", "5-year breakeven inflation rate",
  "5-year breakeven inflation rate", "federal debt: total public debt as percent of gross domestic product",
  "s&p 500", "m2 (discontinued)", "inflation, consumer prices for the united states",
  "real median household income in the united states", "personal consumption expenditures",
  "consumer price index: total all items for the united states",
  "monthly supply of houses in the united states", "consumer price index for all urban consumers: all items less food and energy in u.s. city average",
  "average sales price of houses sold for the united states", "new privately-owned housing units started: total units",
  "personal consumption expenditures: chain-type price index",
  "university of michigan: consumer sentiment", "real personal consumption expenditures",
  "personal consumption expenditures excluding food and energy (chain-type price index)",
  "all-transactions house price index for the united states", "producer price index by industry: plastics material and resins manufacturing",
  "real median personal income in the united states", "real disposable personal income",
  "consumer price index for all urban consumers: used cars and trucks in u.s. city average",
  "university of michigan: inflation expectation", "homeownership rate in the united states",
  "s&p/case-shiller 20-city composite home price index", "advance retail sales: retail trade",
  "unemployment rate - black or african american", "consumer price index for all urban consumers: purchasing power of the consumer dollar in u.s. city average",
  "household debt service payments as a percent of disposable personal income",
  "employment cost index: wages and salaries: private industry workers",
  "employment-population ratio", "consumer price index for all urban consumers: rent of primary residence in u.s. city average",
  "continued claims (insured unemployment)", "personal income",
  "noncyclical rate of unemployment", "retailers: inventories to sales ratio",
  "personal consumption expenditures: durable goods", "real disposable personal income: per capita",
  "unemployment level", "e-commerce retail sales as a percent of total sales",
  "sticky price consumer price index less food and energy", "median consumer price index",
  "motor vehicle retail sales: heavy weight trucks", "all employees, manufacturing",
  "employment level", "disposable personal income", "producer price index by industry: total manufacturing industries",
  "employment-population ratio - 25-54 yrs.", "unemployment rate - 20 yrs. & over, black or african american men",
  "producer price index by industry: semiconductor and other electronic component manufacturing",
  "personal consumption expenditures: services", "producer price index by industry: cement and concrete product manufacturing",
  "industrial production: manufacturing (naics)", "mortgage debt service payments as a percent of disposable personal income",
  "producer price index by industry: glass and glass product manufacturing",
  "producer price index by industry: corrugated and solid fiber box manufacturing: corrugated shipping containers for paper and allied products",
  "manufacturing sector: output for all employed persons", "gross national income for united states",
  "producer price index by industry: chemical manufacturing", "mean personal income in the united states",
  "real personal income", "consumer debt service payments as a percent of disposable personal income",
  "consumer opinion surveys: confidence indicators: composite indicators: oecd indicator for the united states"
), id = c(
  "T10Y2Y", "FEDFUNDS", "CPIAUCSL", "T10YIE", "GDPC1",
  "MORTGAGE30US", "GDP", "DGS10", "UNRATE", "BAMLH0A0HYM2", "WALCL",
  "M2SL", "M1SL", "CSUSHPINSA", "DFII10", "T10Y3M", "M2V", "RRPONTSYD",
  "MSPUS", "T5YIE", "T5YIEM", "GFDEGDQ188S", "SP500", "M2", "FPCPITOTLZGUSA",
  "MEHOINUSA672N", "PCE", "CPALTT01USM657N", "MSACSR", "CPILFESL",
  "ASPUS", "HOUST", "PCEPI", "UMCSENT", "PCEC96", "PCEPILFE", "USSTHPI",
  "PCU325211325211", "MEPAINUSA672N", "DSPIC96", "CUSR0000SETA02",
  "MICH", "RHORUSQ156N", "SPCS20RSA", "RSXFS", "LNS14000006", "CUUR0000SA0R",
  "TDSP", "ECIWAG", "EMRATIO", "CUUR0000SEHA", "CCSA", "PI", "NROU",
  "RETAILIRSA", "PCEDG", "A229RX0", "UNEMPLOY", "ECOMPCTSA", "CORESTICKM159SFRBATL",
  "MEDCPIM158SFRBCLE", "HTRUCKSSAAR", "MANEMP", "CE16OV", "DSPI",
  "PCUOMFGOMFG", "LNS12300060", "LNS14000031", "PCU33443344", "PCES",
  "PCU32733273", "IPMAN", "MDSP", "PCU3272132721", "PCU32221132221102",
  "OUTMS", "MKTGNIUSA646NWDB", "PCU325325", "MAPAINUSA646N", "RPI",
  "CDSP", "CSCICP03USM665S"
), factor = c(
  "Interest Rates", "Interest Rates",
  "Inflation", "Interest Rates", "Others", "Interest Rates", "Others",
  "Interest Rates", "Employment", "Others", "Others", "Others",
  "Others", "Housing & construction", "Interest Rates", "Interest Rates",
  "Others", "Interest Rates", "Housing & construction", "Interest Rates",
  "Interest Rates", "Others", "Others", "Others", "Inflation",
  "Housing & construction", "Retail and Consumption", "Inflation",
  "Housing & construction", "Inflation", "Housing & construction",
  "Housing & construction", "Retail and Consumption", "Surveys",
  "Retail and Consumption", "Retail and Consumption", "Housing & construction",
  "Manufacturing", "Income", "Income", "Inflation", "Inflation",
  "Housing & construction", "Housing & construction", "Retail and Consumption",
  "Employment", "Inflation", "Housing & construction", "Employment",
  "Employment", "Inflation", "Employment", "Income", "Employment",
  "Retail and Consumption", "Retail and Consumption", "Income",
  "Employment", "Retail and Consumption", "Inflation", "Inflation",
  "Retail and Consumption", "Manufacturing", "Employment", "Income",
  "Manufacturing", "Employment", "Employment", "Manufacturing",
  "Retail and Consumption", "Manufacturing", "Manufacturing", "Income",
  "Manufacturing", "Manufacturing", "Manufacturing", "Income",
  "Manufacturing", "Income", "Income", "Income", "Surveys"
)), row.names = c(
  NA,
  -82L
), class = c("tbl_df", "tbl", "data.frame")) -> macro_indicators




usethis::use_data(macro_indicators, overwrite = TRUE)
